import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import {Header} from "./components";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cleanow = Inter({
  variable: "--font-cleanow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Victor Protocol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cleanow.variable} antialiased`}
      >
        <Providers>
          <Header />
        {children}
        </Providers>
      </body>
    </html>
  );
}
